# Model training configuration

# Compression settings
compression: "high"  # Options: "high" (4-bit), "medium" (8-bit), or "low" (16-bit)

# Model settings
model_name: "Qwen/Qwen2.5-0.5B"
target_modules: 
  - "q_proj"
  - "k_proj"
  - "v_proj"
  - "o_proj"

# Dataset settings
dataset: "trl-lib/Capybara"
dataset_split: "train"

# Training parameters
batch_size: 4
learning_rate: 5e-5
num_train_epochs: 3
warmup_steps: 100

# Output settings
output_dir: "./results"
save_dir: "qwen-0.5b-sft-high"
logging_dir: "./logs"

# Weights & Biases integration
use_wandb: true
wandb_project: "trl"
wandb_entity: "nu-llpr"  # Your Weights & Biases username or organization
run_name: "qwen-0.5b-sft-high"
